import PySide6
from PySide6.QtWidgets import QApplication, QPushButton, QWidget, QHBoxLayout , QVBoxLayout ,QGridLayout
import sys
import random

roxo = "purple"
nome = ["viado","puto","cachoro","vaca","filha","garafa","sete","oito","nove","dez","onze","doze","treze","catoze","pililiu","pilulu","talulu","vatutu","dezenove","vinte"]
tela = QApplication(sys.argv)
botao1 = QPushButton(nome[random.randint(0,19)])
botao2 = QPushButton(nome[random.randint(0,19)])
botao3 = QPushButton(nome[random.randint(0,19)])
botao4 = QPushButton(nome[random.randint(0,19)])
botao5 = QPushButton(nome[random.randint(0,19)])
botao6 = QPushButton(nome[random.randint(0,19)])
botao7 = QPushButton(nome[random.randint(0,19)])
botao8 = QPushButton(nome[random.randint(0,19)])
botao9 = QPushButton(nome[random.randint(0,19)])
botao10 = QPushButton(nome[random.randint(0,19)])
botao11 = QPushButton(nome[random.randint(0,19)])
botao12 = QPushButton(nome[random.randint(0,19)])
botao13 = QPushButton(nome[random.randint(0,19)])
botao14 = QPushButton(nome[random.randint(0,19)])
botao15 = QPushButton(nome[random.randint(0,19)])
botao16 = QPushButton(nome[random.randint(0,19)])
botao17 = QPushButton(nome[random.randint(0,19)])
botao18 = QPushButton(nome[random.randint(0,19)])
botao19 = QPushButton(nome[random.randint(0,19)])
botao20 = QPushButton(nome[random.randint(0,19)])
botao1.setStyleSheet("font-size: 10px; color: red")
botao2.setStyleSheet("font-size: 10px; color: red")
botao3.setStyleSheet("font-size: 10px; color: red")
botao4.setStyleSheet("font-size: 10px; color: red")
botao5.setStyleSheet("font-size: 10px; color: red")
botao6.setStyleSheet("font-size: 10px; color: red")
botao7.setStyleSheet("font-size: 10px; color: red")
botao8.setStyleSheet("font-size: 10px; color: red")
botao9.setStyleSheet("font-size: 10px; color: red")
botao10.setStyleSheet("font_size: 10px; color: red")
botao11.setStyleSheet("font_size: 10px; color: red")
botao12.setStyleSheet("font_size: 10px; color: red")
botao13.setStyleSheet("font_size: 10px; color: red")
botao14.setStyleSheet("font_size: 10px; color: red")
botao15.setStyleSheet("font_size: 10px; color: red")
botao16.setStyleSheet("font_size: 10px; color: red")
botao17.setStyleSheet("font_size: 10px; color: red")
botao18.setStyleSheet("font_size: 10px; color: red")
botao19.setStyleSheet("font_size: 10px; color: red")
botao20.setStyleSheet("font_size: 10px; color: red")
cor_aleatoria = random.randint(0,11)
    
janela = QWidget()
lugar_dos_botao = QGridLayout()
janela.setLayout(lugar_dos_botao)
lugar_dos_botao.addWidget(botao1 , 1,1)
lugar_dos_botao.addWidget(botao2 , 1,2)
lugar_dos_botao.addWidget(botao3 , 1,3)
lugar_dos_botao.addWidget(botao4 , 2,1)
lugar_dos_botao.addWidget(botao5 ,2,2)
lugar_dos_botao.addWidget(botao6, 2,3)
lugar_dos_botao.addWidget(botao7 , 3,1)
lugar_dos_botao.addWidget(botao8 , 3,2)
lugar_dos_botao.addWidget(botao9,3,3)
lugar_dos_botao.addWidget(botao10,4,1)
lugar_dos_botao.addWidget(botao11,4,2)
lugar_dos_botao.addWidget(botao12,4,3)
lugar_dos_botao.addWidget(botao13,5,1)
lugar_dos_botao.addWidget(botao14,5,2)
lugar_dos_botao.addWidget(botao15,5,3)
lugar_dos_botao.addWidget(botao16,6,1)
lugar_dos_botao.addWidget(botao17,6,2)
lugar_dos_botao.addWidget(botao18,6,3)
lugar_dos_botao.addWidget(botao19,7,1)
lugar_dos_botao.addWidget(botao12,7,2)


janela.show()

tela.exec()